<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="SpinCore">
      <HintPath>C:\Users\kelvi\AppData\Roaming\SRXD Mod Manager\data\BepInEx\plugins\e175438534a4f36f149d7abfd21ee39f69752a3f8159ae999fe869aaa5318579\SpinCore.dll</HintPath>
    </Reference>
    <Reference Include="SSD.Game">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\SSD.Game.dll</HintPath>
    </Reference>
    <Reference Include="SSD.Types">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\SSD.Types.dll</HintPath>
    </Reference>
    <Reference Include="SSD.Utility">
      <HintPath>..\..\..\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\SSD.Utility.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\..\..\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\..\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\UnityEngine.InputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\..\..\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>G:\Steam\steamapps\common\Spin Rhythm\SpinRhythm_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="locale.json" />
    <EmbeddedResource Include="locale.json" />
  </ItemGroup>
  
  <ItemGroup>
    <None Remove="textshader" />
    <EmbeddedResource Include="Shaders\textshader" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="set gameDirectory=&quot;C:\Users\kelvi\AppData\Roaming\SRXD Mod Manager\data\BepInEx\plugins&quot;&#xA;&#xA;if exist %25gameDirectory%25 (&#xA;    copy /y &quot;$(TargetDir)$(TargetFileName)&quot; %25gameDirectory%25&#xA;) else (&#xA;    ECHO &quot;Destination folder not found, skipping copy.&quot;&#xA;)" />
  </Target>

</Project>
